(function(){
var params = ReportGrid.parseQueryParameters(ReportGrid.findScript('rn-usa-states-path.json.js').src),
	handler = params['callback'];
window[handler]({
"01" : "United States/AL",
"02" : "United States/AK",
"04" : "United States/AZ",
"05" : "United States/AR",
"06" : "United States/CA",
"08" : "United States/CO",
"09" : "United States/CT",
"10" : "United States/DE",
"11" : "United States/DC",
"12" : "United States/FL",
"13" : "United States/GA",
"15" : "United States/HI",
"16" : "United States/ID",
"17" : "United States/IL",
"18" : "United States/IN",
"19" : "United States/IA",
"20" : "United States/KS",
"21" : "United States/KY",
"22" : "United States/LA",
"23" : "United States/ME",
"24" : "United States/MD",
"25" : "United States/MA",
"26" : "United States/MI",
"27" : "United States/MN",
"28" : "United States/MS",
"29" : "United States/MO",
"30" : "United States/MT",
"31" : "United States/NE",
"32" : "United States/NV",
"33" : "United States/NH",
"34" : "United States/NJ",
"35" : "United States/NM",
"36" : "United States/NY",
"37" : "United States/NC",
"38" : "United States/ND",
"39" : "United States/OH",
"40" : "United States/OK",
"41" : "United States/OR",
"42" : "United States/PA",
"44" : "United States/RI",
"45" : "United States/SC",
"46" : "United States/SD",
"47" : "United States/TN",
"48" : "United States/TX",
"49" : "United States/UT",
"50" : "United States/VT",
"51" : "United States/VA",
"53" : "United States/WA",
"54" : "United States/WV",
"55" : "United States/WI",
"56" : "United States/WY",
"60" : "United States/AS",
"66" : "United States/GU",
"69" : "United States/MP",
"72" : "United States/PR",
"78" : "United States/VI",
"64" : "United States/FM",
"68" : "United States/MH",
"70" : "United States/PW"
}
, { status : { code : 200 }})
})();